-- Migration 022: Skills Library
-- Skills are reusable procedural knowledge blocks assigned to agents.
-- They are injected into the task message at execution time (after the project brief,
-- before the assigned subtask), giving agents a structured "how to" for specific work.

CREATE TABLE skills (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT        NOT NULL,
  slug        TEXT        NOT NULL UNIQUE,
  description TEXT        NOT NULL DEFAULT '',
  content     TEXT        NOT NULL,
  category    TEXT        NOT NULL DEFAULT 'general',
  source      TEXT        NOT NULL DEFAULT 'official',  -- 'official' | 'community'
  author      TEXT        NOT NULL DEFAULT 'AitherOS',
  repo_url    TEXT        NOT NULL DEFAULT '',
  version     TEXT        NOT NULL DEFAULT '1.0.0',
  icon        TEXT        NOT NULL DEFAULT '⚡',
  tags        TEXT[]      NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agent_skills (
  agent_id    UUID        NOT NULL REFERENCES agents(id)  ON DELETE CASCADE,
  skill_id    UUID        NOT NULL REFERENCES skills(id)  ON DELETE CASCADE,
  position    SMALLINT    NOT NULL DEFAULT 0,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (agent_id, skill_id)
);

CREATE INDEX idx_agent_skills_agent ON agent_skills(agent_id);
CREATE INDEX idx_skills_category    ON skills(category);
CREATE INDEX idx_skills_source      ON skills(source);

-- ── Official Seed Skills ──────────────────────────────────────────────────────

INSERT INTO skills (name, slug, description, content, category, icon, tags) VALUES

('SEO Content Writing', 'seo-content-writing',
 'Evidence-based framework for producing content that ranks. Covers keyword placement, structure, readability, and on-page signals.',
 E'## SEO Content Writing Framework\n\n**Before writing — research phase:**\n- Identify the primary keyword (target exact-match in: title, H1, first 100 words, one subheading, meta description)\n- Choose 3-5 semantic variants for subheadings (LSI terms, related phrases)\n- Confirm search intent: informational (how/what/why), transactional (buy/get/download), navigational (brand)\n- Check top-3 SERP results for content format (listicle, tutorial, comparison, long-form guide)\n\n**Structure rules:**\n- Title tag: 50-60 chars, primary keyword in first 40 chars\n- Meta description: 140-160 chars, include primary keyword + one concrete benefit + CTA\n- H1: matches title intent, NOT identical copy\n- Subheadings (H2/H3): use keyword variants, frame as questions where natural\n- Introduction: hook in first sentence, primary keyword by sentence 2, preview of value\n- Conclusion: summarize, CTA, internal link to next logical page\n\n**Content quality signals:**\n- Minimum 300 words per H2 section for pillar content\n- Flesch reading score > 60 (short sentences, active voice)\n- Keyword density 0.5–1.5% (avoid stuffing)\n- Every image needs a descriptive alt tag with keyword where natural\n- Include at least one data point, statistic, or citation per major claim\n- Internal links: 2-4 to semantically related pages\n- External links: 1-2 to authoritative sources (avoid direct competitors)\n\n**Featured snippet targeting:**\n- For "what is" queries: lead with a 40-60 word definition paragraph\n- For "how to" queries: use a numbered list with 5-8 steps\n- For comparison queries: use a table with 3-5 attributes\n\n**Before submitting:**\n- All headers form a logical outline readable on their own\n- No orphan sections (each H2 has at least 2 H3s or 300+ words)\n- Exact primary keyword appears in slug/URL',
 'writing', '✍️', ARRAY['seo', 'content', 'writing', 'marketing']),

('Security Reconnaissance', 'security-recon',
 'Structured methodology for passive and active reconnaissance following PTES and OWASP guidelines.',
 E'## Security Reconnaissance Methodology\n\n**Phase 1 — Passive Recon (no direct target contact):**\n- OSINT: search for target domains, subdomains, employee names, job postings (reveal tech stack)\n- Certificate transparency logs (crt.sh): enumerate subdomains without DNS queries\n- Shodan/Censys: identify exposed services, banners, TLS cert details\n- WHOIS + reverse WHOIS: map IP ranges, registrant data, related domains\n- Google dorking: site:target.com filetype:pdf/xlsx, inurl:admin, intitle:"index of"\n- GitHub/GitLab search: leaked credentials, API keys, internal hostnames in commit history\n- Wayback Machine: discover removed endpoints, old API versions, forgotten subdomains\n\n**Phase 2 — Active Recon (direct contact, ensure authorization):**\n- DNS enumeration: A, MX, TXT, CNAME, NS records; zone transfer attempt\n- Port scanning: TCP SYN scan top-1000 ports, then full range on interesting hosts\n- Service fingerprinting: banner grabbing, version detection (-sV), OS detection (-O)\n- Web crawling: identify all endpoints, forms, parameters, JS files\n- Technology fingerprinting: Wappalyzer equivalents, HTTP headers (Server, X-Powered-By), cookies\n\n**Documentation requirements:**\n- Record every finding with: timestamp, tool used, exact command, raw output snippet\n- Maintain a running asset inventory: IP → hostname → open ports → service → version\n- Flag high-value targets immediately: admin panels, VPN endpoints, mail servers, CI/CD\n- Note authentication mechanisms observed (basic auth, OAuth, JWT, session cookies)\n\n**Rules of engagement checklist:**\n- Confirm written authorization covers the current target scope before any active scan\n- Stay within declared IP ranges — verify with each new subnet discovered\n- Stop and report immediately if live production data is encountered unexpectedly\n- Log all actions with timestamps for the engagement report',
 'security', '🔒', ARRAY['security', 'recon', 'pentest', 'osint']),

('Code Review', 'code-review',
 'Systematic approach to reviewing code for correctness, security, performance, and maintainability.',
 E'## Code Review Framework\n\n**Review order (highest risk first):**\n1. Security vulnerabilities (injection, auth bypass, data exposure)\n2. Logic errors and edge cases (nulls, empty inputs, off-by-one, race conditions)\n3. Error handling (all failure paths handled, no silent failures)\n4. Performance (N+1 queries, unbounded loops, missing indexes, unnecessary allocations)\n5. Readability and maintainability (naming, complexity, duplication)\n6. Test coverage (critical paths tested, mocks vs real dependencies)\n\n**Security checklist (check every change that touches these):**\n- User input: validated, sanitized, never concatenated into SQL/shell/HTML\n- Auth: every endpoint checks authentication AND authorization separately\n- Secrets: no hardcoded credentials, API keys, or tokens in code\n- Dependencies: no new dependencies with known CVEs; minimal scope\n- Data exposure: API responses don''t leak internal fields, stack traces, or PII\n\n**What to always call out:**\n- Any TODO/FIXME left in production-bound code — require resolution or ticket\n- Functions over 40 lines — flag for extraction\n- Cyclomatic complexity > 10 — flag for simplification\n- Missing error returns in Go / uncaught Promise rejections in JS\n- Tests that mock the database (prefer integration tests for data layer)\n\n**Tone and format for feedback:**\n- Lead with the category: [BUG], [SECURITY], [PERF], [STYLE], [QUESTION]\n- One issue per comment, include line reference\n- For blocking issues: explain WHY it is a problem + suggest the fix\n- For style issues: "consider" language, not directives\n- Always acknowledge what is done well — balance critical feedback\n\n**Sign-off criteria:**\n- Zero [BUG] and [SECURITY] comments unresolved\n- All [PERF] items either fixed or explicitly accepted with reasoning\n- Tests cover the changed behavior',
 'engineering', '🔍', ARRAY['code', 'review', 'engineering', 'quality']),

('Technical Documentation', 'technical-documentation',
 'Framework for writing clear, complete technical documentation: APIs, guides, runbooks, and READMEs.',
 E'## Technical Documentation Framework\n\n**Before writing — audience and purpose:**\n- Who is the reader? (developer, operator, end user, future self)\n- What is their starting knowledge level?\n- What do they need to DO after reading this? (install, integrate, debug, decide)\n- What format fits? (README, API reference, tutorial, runbook, ADR)\n\n**README structure (in order):**\n1. One-sentence description (what it does, not how)\n2. Quick start: working example in < 5 commands\n3. Prerequisites: exact versions, not "recent version"\n4. Installation: copy-pasteable commands, no implicit steps\n5. Configuration: all env vars / config keys with type, default, and example\n6. Usage: the 3 most common use cases with full examples\n7. API reference (if applicable): every endpoint, parameter, response\n8. Troubleshooting: the 5 most common errors + resolution\n9. Contributing: how to run tests, PR expectations\n\n**API documentation rules:**\n- Every endpoint: method, path, auth requirement, request schema, response schema, error codes\n- Every parameter: name, type, required/optional, validation constraints, example value\n- Every response: status code meaning, full example JSON (real values, not "string")\n- Rate limits, pagination, and versioning policy must be documented\n\n**Writing quality rules:**\n- Present tense: "returns" not "will return"\n- Active voice: "call this endpoint" not "this endpoint should be called"\n- Code examples: complete, copy-pasteable, with real values (not <YOUR_API_KEY>)\n- No jargon without definition on first use\n- One concept per paragraph\n- All file paths, commands, and identifiers in backtick formatting\n\n**Runbook / operational guide extras:**\n- Every procedure starts with: trigger condition, expected duration, rollback steps\n- Every command includes: expected output and what failure looks like\n- On-call escalation path and contacts at the top',
 'writing', '📄', ARRAY['documentation', 'writing', 'technical', 'api']),

('Data Analysis', 'data-analysis',
 'Structured approach to exploratory data analysis, statistical reasoning, and insight communication.',
 E'## Data Analysis Framework\n\n**Phase 1 — Understand the data:**\n- Shape: rows × columns, dtypes, memory footprint\n- Completeness: null rates per column — any > 5% needs a strategy (impute, drop, flag)\n- Distributions: min, max, mean, median, std for numeric; value_counts for categoricals\n- Duplicates: exact duplicates + near-duplicates on key identifiers\n- Temporal coverage: if time-series, gaps, seasonality, timezone consistency\n\n**Phase 2 — Validate assumptions:**\n- Check every join for cardinality (1:1, 1:N, N:M) — unexpected N:M = data quality issue\n- Verify business key uniqueness before aggregating\n- Sanity-check totals against known benchmarks (revenue should match finance reports)\n- Flag any rows that violate expected constraints (negative prices, future birth dates)\n\n**Phase 3 — Analysis:**\n- State the question in one sentence before each analysis block\n- Show the calculation method, not just the result\n- For comparisons: use the same denominator (% vs absolute counts can mislead)\n- Correlation ≠ causation: flag any causal claim that isn''t from an experiment\n- Segment before averaging: an average across heterogeneous groups hides signal\n\n**Phase 4 — Communicate findings:**\n- Lead with the answer, then the evidence (inverted pyramid)\n- Every chart needs: title (the finding, not the metric), axis labels with units, data source\n- Use tables for exact values, charts for trends and comparisons\n- Include confidence: "likely" vs "certain" — distinguish exploratory from confirmatory\n- Recommended action per finding: what should change based on this insight?\n\n**Caveats to always include:**\n- Sample size and time period of the data\n- Known data quality issues and their potential impact\n- What this analysis cannot answer',
 'analytics', '📊', ARRAY['data', 'analysis', 'analytics', 'statistics']),

('Growth Hacking', 'growth-hacking',
 'Frameworks for rapid experimentation, funnel analysis, and growth loop design for early-stage products.',
 E'## Growth Hacking Framework\n\n**The AARRR funnel — measure before optimizing:**\n- Acquisition: where do users come from? (channel, campaign, organic vs paid)\n- Activation: do new users reach the "aha moment"? (define it precisely — first value delivery)\n- Retention: do they come back? (D1, D7, D30 cohort retention rates)\n- Revenue: do they pay? (conversion rate, ARPU, LTV)\n- Referral: do they bring others? (NPS, K-factor, viral coefficient)\n- Find the weakest stage first — fixing acquisition when retention is broken wastes money\n\n**Experiment design rules:**\n- One variable per experiment (never test copy + design + CTA simultaneously)\n- Define success metric and minimum effect size BEFORE running the experiment\n- Calculate required sample size for 80% power at p < 0.05 before starting\n- Run for full business cycles (at least 2 weeks for B2B, 1 week for high-traffic B2C)\n- Document: hypothesis, control, variant, metric, result, decision\n\n**High-leverage growth levers (test in this order):**\n1. Onboarding optimization: reduce steps to aha moment\n2. Activation email sequence: 3-email sequence triggered on signup\n3. In-product referral: show referral CTA at moment of highest value\n4. Pricing page optimization: social proof, anchoring, clear tier differentiation\n5. SEO content targeting bottom-of-funnel keywords\n\n**Content and SEO for growth:**\n- Bottom-of-funnel first: "[product] vs [competitor]", "best [category] for [use case]"\n- Middle-of-funnel: how-to guides that demonstrate product capability\n- Top-of-funnel: only after bottom and middle are producing results\n- Distribution > creation: one post promoted to 10 channels beats 10 posts promoted nowhere\n\n**Red flags to avoid:**\n- Vanity metrics (page views, social followers) over activation and retention\n- Running experiments without statistical significance\n- Optimizing a leaky funnel instead of fixing the leak',
 'marketing', '📈', ARRAY['growth', 'marketing', 'analytics', 'experiments']);
