const brandMap: Record<string, string> = {
  github: 'github',
  gitlab: 'gitlab',
  bitbucket: 'bitbucket',
  slack: 'slack',
  discord: 'discord',
  teams: 'microsoftteams',
  notion: 'notion',
  linear: 'linear',
  jira: 'jira',
  confluence: 'confluence',
  trello: 'trello',
  asana: 'asana',
  monday: 'monday',
  clickup: 'clickup',
  figma: 'figma',
  google: 'google',
  gmail: 'gmail',
  'google drive': 'googledrive',
  'google docs': 'googledocs',
  'google sheets': 'googlesheets',
  'google calendar': 'googlecalendar',
  'google cloud': 'googlecloud',
  gcp: 'googlecloud',
  aws: 'amazonaws',
  amazon: 'amazonaws',
  azure: 'microsoftazure',
  microsoft: 'microsoft',
  docker: 'docker',
  kubernetes: 'kubernetes',
  k8s: 'kubernetes',
  postgres: 'postgresql',
  postgresql: 'postgresql',
  mysql: 'mysql',
  mongodb: 'mongodb',
  redis: 'redis',
  elasticsearch: 'elasticsearch',
  stripe: 'stripe',
  twilio: 'twilio',
  sendgrid: 'sendgrid',
  mailchimp: 'mailchimp',
  vercel: 'vercel',
  netlify: 'netlify',
  supabase: 'supabase',
  airtable: 'airtable',
  zapier: 'zapier',
  salesforce: 'salesforce',
  hubspot: 'hubspot',
  shopify: 'shopify',
  cloudflare: 'cloudflare',
  datadog: 'datadog',
  grafana: 'grafana',
  prometheus: 'prometheus',
  openai: 'openai',
  anthropic: 'anthropic',
  pagerduty: 'pagerduty',
  opsgenie: 'opsgenie',
  sentry: 'sentry',
  newrelic: 'newrelic',
  'new relic': 'newrelic',
  npm: 'npm',
  yarn: 'yarn',
  terraform: 'terraform',
  ansible: 'ansible',
  jenkins: 'jenkins',
  circleci: 'circleci',
  'github actions': 'githubactions',
  wordpress: 'wordpress',
  firebase: 'firebase',
  twitch: 'twitch',
  youtube: 'youtube',
  twitter: 'x',
  x: 'x',
  linkedin: 'linkedin',
  instagram: 'instagram',
  facebook: 'facebook',
  whatsapp: 'whatsapp',
  telegram: 'telegram',
  dropbox: 'dropbox',
  box: 'box',
  onedrive: 'onedrive',
  icloud: 'icloud',
  heroku: 'heroku',
  digitalocean: 'digitalocean',
  linode: 'linode',
  vultr: 'vultr',
  sqlite: 'sqlite',
  planetscale: 'planetscale',
  neon: 'neon',
  hasura: 'hasura',
  graphql: 'graphql',
  obsidian: 'obsidian',
  todoist: 'todoist',
  evernote: 'evernote',
  oura: 'oura',
  apple: 'apple',
};

export function getMcpBrandIconUrl(serverName: string, color = 'ffffff'): string | null {
  const lower = serverName.toLowerCase();
  for (const [key, slug] of Object.entries(brandMap)) {
    if (lower.includes(key)) {
      return `https://cdn.simpleicons.org/${slug}/${color}`;
    }
  }
  return null;
}
